/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ewalletSol from "./Ewallet.sol";
export type { ewalletSol };
export type { INToken } from "./INToken";
export type { Lock } from "./Lock";
export type { MintableToken } from "./MintableToken";
